---
- name: ensure dependencies are present
  apt:
    name: apt-transport-https
    state: installed

- name: import erlang apt key
  apt_key:
    url: "https://packages.erlang-solutions.com/debian/erlang_solutions.asc"

- name: add erlang solutions repository
  apt_repository:
    repo: "deb https://packages.erlang-solutions.com/{{ ansible_distribution | lower }} {{ ansible_distribution_release | lower }} contrib"

- name: install erlang
  apt:
    name: erlang

- name: import rabbitmq apt key
  apt_key:
    url: https://www.rabbitmq.com/rabbitmq-release-signing-key.asc

- name: download rabbitmq package
  get_url:
    url: "https://www.rabbitmq.com/releases/rabbitmq-server/v{{ rabbitmq_version.split('-')[0] }}/rabbitmq-server_{{ rabbitmq_version }}{% if rabbitmq_version | version_compare('3.6.6', '>=') %}{% endif %}_all.deb"
    dest: "/usr/src/rabbitmq-server-{{ rabbitmq_version }}.deb"

- name: install rabbitmq
  apt:
    deb: "/usr/src/rabbitmq-server-{{ rabbitmq_version }}.deb"
